CREATE DATABASE teaspoon_personal;

USE teaspoon_personal;

CREATE TABLE notice(
	seq INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	content VARCHAR(1000) NOT NULL,
	regDate DATETIME DEFAULT CURRENT_TIMESTAMP(),
	visited INT DEFAULT 0
);
